// RAS(RİB) - CİB-RMU-FM(RIB)-01-2026, versiya 01, 31/07/2026 (RIB vərəqi)
// 21 Risk İştahası Bəyanatı göstəricisi, sənəddəki ardıcıllıqla.
// Məzmun sahələri (ad, bəyanat, formul, sahib, mənbə, vahid, qeyd) sənəddəki
// kimi Azərbaycan dilindədir - interfeysin özü İngilis dilində qalır.
// period_values Q1/Q2 aylıq oxunuşlarıdır; null = ay bildirilməyib (0 deyil).
import type { KRIItem } from '@/types'

const NOW = new Date().toISOString()

export const SEED_RAS_KRIS: KRIItem[] = [
  {
    id: "a5000000-0000-4000-8000-000000000001",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-001",
    name: "Mediada yayımlanan neqativ və imic zədələyici məlumatlar",
    description: "Büro Kütləvi İnformasiya Vasitələrində yayımlanan mənfi xəbərlərin, məlumatların və şərhlərin təsiri ilə bağlı aşağı dözümlülük prinsipi tətbiq edir. Çox yüksək reputasiya riskləri yaradan məzmunlara qarşı sıfır tolerans risk strategiyası seçilmişdir və belə halların monitorinqi, qiymətləndirilməsi və operativ cavab tədbirləri şirkətin kommunikasiyalar və risk idarəetməsi prosedurlarına uyğun həyata keçirilir. Risk qəbul etmə siyasətinə uyğun olaraq dərəcələndirilmiş (yüksək və çox yüksək risklər istisna olmaqla) və qısa müddətli mənfi məlumatlar isə müəyyən edilmiş idarəetmə mexanizmləri çərçivəsində qəbul edilə bilər.",
    risk_category: "reputation",
    formula: "(Dövr ərzində KIV(Kütləvi İnformasiya Vasitələri) yayımlanmış mənfi xəbər, məlumat və şərhlər/Dövr ərzində ümumi Media Məlumatları) x100%",
    data_source: "Media monitorinq sistemi",
    risk_owner: "İctimaiyyətlə əlaqələr və Kommunikasiya Şöbəsi",
    unit: "Faiz",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "<4%",
    threshold_amber: "4%-5%",
    threshold_red: ">5%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000002",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-002",
    name: "Mediada yayımlanan neqativ və imic zədələyici məlumatlar",
    description: "Büro Kütləvi İnformasiya Vasitələrində yayımlanan mənfi xəbərlərin, məlumatların və şərhlərin təsirinə qarşı aşağı dözümlülük prinsipini tətbiq edir. Çox yüksək və yüksək reputasiya riskləri yaradan məzmunun 5 gündən uzun müddət mediada qalması Büro üçün qəbul edilməzdir və belə hallara qarşı monitorinq, qiymətləndirmə və operativ cavab tədbirləri şirkətin kommunikasiya və risk idarəetməsi siyasətinə uyğun həyata keçirilir. Risk qəbul etmə siyasətinə uyğun olaraq dərəcələndirilmiş (yüksək və çox yüksək risklər istisna olmaqla) və qısa müddətli mənfi məlumatlar isə müəyyən edilmiş idarəetmə mexanizmləri çərçivəsində qəbul edilə bilər.",
    risk_category: "reputation",
    formula: "Dövr ərzində KIV-də (Kütləvi İnformasiya Vasitələri) Büro haqqında yayımlanmış mənfi məlumatların mediada gündəmdə qalma müddəti",
    data_source: "Media monitorinq sistemi",
    risk_owner: "İctimaiyyətlə əlaqələr və Kommunikasiya Şöbəsi",
    unit: "Gün",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "≤3",
    threshold_amber: "4-5",
    threshold_red: ">5",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000003",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-003",
    name: "Bərpa müddəti (RTO)",
    description: "Büro kritik biznes prosesləri üzrə xidmətin dayanmasına qarşı aşağı risk iştahasına malikdir və bir hadisə üzrə xidmətin bərpa müddətinin 2 saatdan artıq olmasına tolerantlıq göstərmir.",
    risk_category: "information_security",
    formula: "Dövr ərizində Sistemdə baş vermiş ümumi dayanma və dayanma üzrə bərpa müddəti",
    data_source: "İnformasiya təhlükəsizlik alətləri",
    risk_owner: "Baş informasiya inzibatçısı",
    unit: "Saat",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0.43,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "<1",
    threshold_amber: "1-2",
    threshold_red: ">2",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000004",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-004",
    name: "Bərpa nöqtəsi göstəricisi (RPO)",
    description: "Təşkilat kritik informasiya sistemləri üzrə məlumat itkisinə qarşı sıfır tolerans göstərir.Sıfır tolerans tələbinə görə istənilən 0-dan böyük dəyər limit pozuntusu hesab edilir.",
    risk_category: "information_security",
    formula: "Dövr ərizində hadisə (kəsinti, sistemin sıradan çıxması, kiber-insident və s.) baş verdikdə, qəbul edilən maksimum məlumat itkisi müddəti (Back up strategiyasına uyğun)",
    data_source: "İnformasiya təhlükəsizlik alətləri",
    risk_owner: "Baş informasiya inzibatçısı",
    unit: "Saat",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "0",
    threshold_amber: "0",
    threshold_red: ">0",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000005",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-005",
    name: "Bərpa nöqtəsi göstəricisi (RPO)",
    description: "Kritik informasiya sistemləri üzrə RPO tələbinə uyğun olaraq, maksimum xidmət verilməmə müddəti 2 saatdan artıq olmasını qəbul etmir.",
    risk_category: "information_security",
    formula: "RPO - Dövr ərzində sektora təsir edən kritik sistemlərdə xidmət verilməmə müddəti (məlumat itkisi göstəricisi)",
    data_source: "İnformasiya təhlükəsizlik alətləri",
    risk_owner: "Baş informasiya inzibatçısı",
    unit: "Saat",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0.43,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "<1",
    threshold_amber: "1-2",
    threshold_red: ">2",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000006",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-006",
    name: "Həssas məlumatların ötürülməsi(DLP)",
    description: "Həssas məlumatların (açıq informasiya kateqoriyasına daxil olmayan konfidensial informasiya hesab edilən məlumatların, fərdi məlumatların və sığorta məlumatlarının) digər tərəflərə ötürülməsinə yol verilmir.Sıfır tolerans tələbinə görə istənilən 0-dan böyük dəyər limit pozuntusu hesab edilir.",
    risk_category: "information_security",
    formula: "Dövr ərzində cəhd və reallaşma (fiziki yollar ilə və ya elektron şəkildə həssas və konfidensial məlumatların sızdırılması, ötürülməsi  sayı)",
    data_source: "İnformasiya təhlükəsizlik alətləri",
    risk_owner: "İnformasiya təhlükəsizliyi üzrə baş inzibatçı",
    unit: "Dəfə",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "0",
    threshold_amber: "0",
    threshold_red: ">0",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000007",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-007",
    name: "Sektora təsir edən iş prosesində dayanmalar",
    description: "Dövr ərzində iş prosesi üzrə sektora təsir edən kritik sistemlərdə ümumi planlaşdırılmamış dayanma sayı 4 dəfədən artıq olmamalıdır.",
    risk_category: "information_security",
    formula: "Dövr ərzində iş prosesi üzrə planlaşdırılmamış dayanma sayı",
    data_source: "İnformasiya təhlükəsizlik alətləri",
    risk_owner: "Baş informasiya inzibatçısı",
    unit: "Dəfə",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,1,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "≤1",
    threshold_amber: "2-3",
    threshold_red: "≥4",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000008",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-008",
    name: "Sektora təsir edən iş prosesində dayanmalar",
    description: "Dövr ərzində iş prosesi üzrə sektora təsir edən kritik sistemlərdə planlaşdırılmamış ümumi dayanma müddəti 4 saatı aşmamalıdır.",
    risk_category: "information_security",
    formula: "Dövr ərzində iş prosesi üzrə planlaşdırılmamış dayanma müddəti",
    data_source: "İnformasiya təhlükəsizlik alətləri",
    risk_owner: "Baş informasiya inzibatçısı",
    unit: "Saat",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0.43,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "<2",
    threshold_amber: "2-4",
    threshold_red: ">4",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000009",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-009",
    name: "Dövr ərzində baş verən risk və hadisələrin, audit tapıntılarının aradan qaldırılması",
    description: "Büro dövr ərzində icrası gecikmiş bütün çox yüksək  və yüksək hadisələrin sayına və faizinə qarşı aşağı dözümlülük prinsipini tətbiq edir. Hər hansı bir dövrdə çox yüksək və yüksək qiymətləndirilmiş hadisələrin, risklərin və audit tapıntılarının faizi müəyyən edilmiş həddi aşdıqda, operativ araşdırma və qarşısının alınması tədbirləri həyata keçirilir və dərhal eskalasiya edilir. Minimal, aşağı və orta  hadisələr, audit tapıntıları və risklər müəyyən edilmiş prosedurlar çərçivəsində izlənir və idarə olunur",
    risk_category: "compliance",
    formula: "(Dövr ərzində icrası gecikmiş yüksək və çox yüksək dərəcəli risklər və hadisələr, audit tapıntıları /  Dövr ərzində həllini gözləyən yüksək və çox yüksək dərəcəli risklər və hadisələr,audit tapıntıları) x100%",
    data_source: "JİRA",
    risk_owner: "Risklərin idarə edilməsi Şöbəsi",
    unit: "Faiz",
    frequency: "quarterly",
    current_value: 0.005,
    previous_value: 0.0075,
    period_values: {"Q1":[0.01,0.006,0.006],"Q2":[0.011,0.0075,0.005]},
    trend: "down",
    threshold_green: "<5%",
    threshold_amber: "5%-15%",
    threshold_red: ">15%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000010",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-010",
    name: "Cavablandırılmamış Zənglər",
    description: "Müştəri xidmətlərinin fasiləsizliyini təmin etmək məqsədilə cavablandırılmamış zənglərin səviyyəsi 10%-dən çox olmamalıdır. 10%-dən yuxarı göstəricilər dərhal düzəldici tədbirlər tələb edir.",
    risk_category: "compliance",
    formula: "(Dövr ərzində cavablandırılmamış zənglər / Dövr ərzində ümumi daxil olan zənglər) x100%",
    data_source: "Şikayət/Hadisə qeydiyyat sistemi",
    risk_owner: "Əməliyyatlar Departamenti",
    note: "Yanvar ayı ərzində buraxılmış zənglər üzrə göstərici 8% olmuş və xəbərdarlıq zonasına daxil olmuşdur. Bununla əlaqəli olaraq struktur ilə eskalasiya edilmiş, İcraçı direktor məlumatlandırılmışdır. Görüşlər keçirilmiş, tədbirlər planı icra edilmişdir. Buraxılmış zənglər üçün limitlər nəzərdən keçirilmiş və prosedurda əks etdirilmişdir.",
    unit: "Faiz",
    frequency: "monthly",
    current_value: 0.0078,
    previous_value: 0.0078,
    period_values: {"Q1":[0.08,0.0424,0.0089],"Q2":[0.01,0.0078,0.0078]},
    trend: "flat",
    threshold_green: "<5%",
    threshold_amber: "5%-10%",
    threshold_red: ">10%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000011",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-011",
    name: "İşçi dövriyyəsi  (turnover)",
    description: "Təşkilat işçi dövriyyəsini (turnover) idarə olunan səviyyədə saxlamağı hədəfləyir və əmək bazarının təbii dəyişkənliyini nəzərə alaraq 20% həddə qədər işçi itkilərini qəbul edir. Lakin turnover səviyyəsinin həddindən artıq artması təşkilat daxilində əməliyyat sabitliyinə, bilik davamlılığına və xidmət keyfiyyətinə mənfi təsir göstərdiyi üçün bu göstərici risk iştahı çərçivəsində aktiv şəkildə monitorinq edilir və müəyyən edilmiş limitlər aşılarsa idarəetmə tədbirləri görülür.",
    risk_category: "operational",
    formula: "(Dövr ərzində işdən ayrılan işçi sayı/ 12 aylıq orta işçi sayı) x100%",
    data_source: "İTSM, 1C ERP",
    risk_owner: "İnsan Resursları Şöbəsi",
    unit: "Faiz",
    frequency: "monthly",
    current_value: 0.0167,
    previous_value: 0,
    period_values: {"Q1":[0.0103,0.0099,0],"Q2":[0,0,0.0167]},
    trend: "up",
    threshold_green: "<10%",
    threshold_amber: "10%-20%",
    threshold_red: ">20%",
    current_status: "green",
    appetite_limit: "Orta",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000012",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-012",
    name: "Kritik İşçi dövriyyəsi  (turnover)",
    description: "Büro dövr ərzində işçi dövriyyəsinə qarşı aşağı dözümlülük prinsipini tətbiq edir. Dövr ərzində çıxan kritik işçilərin faizi müəyyən edilmiş həddi aşdıqda, İnsan Resursları Komitəsi dərhal səbəbləri araşdırır və uyğun düzəldici tədbirlər həyata keçirir.",
    risk_category: "operational",
    formula: "(Dövr ərzində işdən ayrılan  kritik işçi sayı/12 aylıq orta kritik  işçi sayı) x100%",
    data_source: "İTSM, 1C ERP",
    risk_owner: "İnsan Resursları Şöbəsi",
    unit: "Faiz",
    frequency: "monthly",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0.037,0.037],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "<5%",
    threshold_amber: "5%-10%",
    threshold_red: ">10%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000013",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-013",
    name: "Əməliyyat zərərləri",
    description: "Şirkət əməliyyat zərərləri üzrə aşağı risk iştahasına malikdir. Əməliyyat zərərlərinin məbləği və tezliyi müəyyən edilmiş limitlər daxilində saxlanılmalı, təkrarlanan hadisələr minimuma endirilməli və bütün əhəmiyyətli əməliyyat hadisələri vaxtında araşdırılaraq düzəldici tədbirlər həyata keçirilməlidir. Şirkət daxili nəzarət çatışmazlıqları, fırıldaqçılıq və ciddi proses pozuntuları nəticəsində yaranan əməliyyat zərərlərinə qarşı sıfır tolerantlıq tətbiq edir.",
    risk_category: "operational",
    formula: "Dövr ərzində qeydiyyata alınmış baş verən əməliyyat zərərlərinin ümumi məbləği",
    data_source: "1C ERP",
    risk_owner: "Maliyyə Şöbəsi",
    unit: "AZN",
    frequency: "annual",
    current_value: 0,
    previous_value: 0,
    period_values: {"Q1":[0,0,0],"Q2":[0,0,0]},
    trend: "flat",
    threshold_green: "<10000",
    threshold_amber: "10000-100 000",
    threshold_red: ">100 000",
    current_status: "green",
    appetite_limit: "Orta",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000014",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-014",
    name: "Açıq valyuta mövqeyi",
    description: "Valyuta üzrə aktiv və öhdəliklərin fərqinə qarşı aşağı dözümlülük prinsipi tətbiq edilir. Dövr ərzində valyuta aktivləri ilə öhdəliklər arasındakı fərq müəyyən edilmiş həddi aşarsa, riskin idarə olunması tədbirləri dərhal aktivləşdirilir.",
    risk_category: "financial",
    formula: "(Net açıq valyuta mövqeyi/Kapital) x100%",
    data_source: "1C ERP",
    risk_owner: "Maliyyə Şöbəsi",
    note: "Təşkilatda requlyativ kapital mövcud olmadığı üçün hesablanma zamanı ümumi kapital əsas götürülür.",
    unit: "Faiz",
    frequency: "annual",
    period_values: {"Q1":[null,null,null],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: "<5%",
    threshold_amber: "5–10%",
    threshold_red: ">10%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000015",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-015",
    name: "Likvidlik çatışmazlığı",
    description: "Şirkət qısamüddətli likvidlik öhdəliklərini vaxtında və tam yerinə yetirmək üçün kifayət qədər yüksək keyfiyyətli likvid aktivlər saxlamağı hədəfləyir.  Şirkət likvidlik göstəricisinin müəyyən edilmiş minimum səviyyədən (100%) aşağı düşməsini qəbul etmir və belə hallarda dərhal likvidlik bərpa planı işə salınır.",
    risk_category: "financial",
    formula: "LCR = (HQLA / Net Cash Outflow, 30 gün) x100% Likvidliyin Örtülməsi Əmsalı = (Yüksək keyfiyyətli likvid aktivlər / Növbəti 30 təqvim günü üzrə ümumi xalis pul vəsaitlərinin çıxışı) x 100%",
    data_source: "1C ERP",
    risk_owner: "Maliyyə Şöbəsi",
    unit: "Faiz",
    frequency: "annual",
    current_value: 494.941416898454,
    previous_value: 512.271054565941,
    period_values: {"Q1":[441.9,622.9,512.271054565941],"Q2":[494.941416898454,null,null]},
    trend: "down",
    threshold_green: ">120%",
    threshold_amber: "120%-100%",
    threshold_red: "<100%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000016",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-016",
    name: "İnvestisiya portfeli üzrə gözlənilən kredit zərəri",
    description: "Büro investisiya portfelinin idarə olunması zamanı portfel riskinin minimumda saxlanılmasını prioritetləşdirir və investisiya siyasətini konservativ şəkildə hazırlamışdır.",
    risk_category: "financial",
    formula: "ECL (kredit zərərləri üçün ehtiyat) balansı/ Ümumi investisiya portfeli) x100%",
    data_source: "1C ERP",
    risk_owner: "Maliyyə Şöbəsi",
    unit: "Faiz",
    frequency: "annual",
    current_value: 0.0044,
    previous_value: 0.0044,
    period_values: {"Q1":[0.0044,0.0044,0.0044],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: "<1%",
    threshold_amber: "1-2%",
    threshold_red: ">2%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000017",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-017",
    name: "Ehtiyat Adekvatlığı",
    description: "Büro ehtiyat çatışmazlığını qəbul etmir",
    risk_category: "market",
    formula: "Ehtiyat Adekvatlığı Nisbəti= (Qarantiya Fondunun texniki ehtiyatları/Gözlənilən Öhdəliklər) ​x100%",
    data_source: "Database (verilənlər bazası)",
    risk_owner: "Aktuar",
    unit: "Faiz",
    frequency: "annual",
    period_values: {"Q1":[null,null,null],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: ">110%",
    threshold_amber: "100–110%",
    threshold_red: "<100%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000018",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-018",
    name: "Qarantiya Fondunun stress dayanıqlılığı",
    description: "Fond istənilən vaxt ən azı 1 ən böyük iştirakçı sığortaçının öhdəliklərini yerinə yetirə bilməməsi ssenarisində rezolusiya qaydalarına və hüquqi olaraq təsdiq edilmiş bütün qanuni öhdəliklərini yerinə yetirəcək maliyyə dayanıqlığını saxlamalıdır. Stress-test nəticəsində əhatə əmsalı 100%-dən aşağı düşməməlidir.",
    risk_category: "market",
    formula: "(Mövcud Qarantiya Fondu / Stress ssenarisində Fond tərəfindən ödənilməsi tələb olunan öhdəlik) x100%",
    data_source: "Database (verilənlər bazası)",
    risk_owner: "Aktuar",
    unit: "Faiz",
    frequency: "annual",
    period_values: {"Q1":[null,null,null],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: ">110%",
    threshold_amber: "100%-110%",
    threshold_red: "<100%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000019",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-019",
    name: "Qarantiya fondunun likvidliyi",
    description: "Likvid aktivlər icbari sığorta bazarı üzrə ehtiyatların minimum 5%-ni təşkil etməlidir ki, qısa müddətli ödəniş öhdəlikləri gecikmədən icra olunsun.",
    risk_category: "market",
    formula: "(Likvid aktivlər / İcbari sığorta üzrə bazar ehtiyatı ) x100%",
    data_source: "Database (verilənlər bazası)",
    risk_owner: "Aktuar",
    unit: "Faiz",
    frequency: "annual",
    period_values: {"Q1":[null,null,null],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: ">10%",
    threshold_amber: "5%-10%",
    threshold_red: "<5%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000020",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-020",
    name: "Qarantiya Fondunun IBNR ehtiyatını qarşılama",
    description: "Baş vermiş, lakin bildirilməmiş zərərlər (IBNR) ehtiyatının bazar ehtiyatına nisbəti aktuar hesablamalarla müəyyən edilmiş diapazonda 100% limit həddində saxlanılmalıdır. Bu diapazondan kənara çıxma ehtiyatların yenidən qiymətləndirilməsini tələb edir.",
    risk_category: "market",
    formula: "(Qarantiya Fondunun vəsaiti/IBNR ehtiyatı) x100%",
    data_source: "Database (verilənlər bazası)",
    risk_owner: "Aktuar",
    unit: "Faiz",
    frequency: "annual",
    period_values: {"Q1":[null,null,null],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: ">110%",
    threshold_amber: "100%-110%",
    threshold_red: "<100%",
    current_status: "green",
    appetite_limit: "Orta",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "a5000000-0000-4000-8000-000000000021",
    org_id: "00000000-0000-0000-0000-000000000001",
    kri_id: "RAS-021",
    name: "Qarantiya Fondunun bazar təminat",
    description: "Fondun maliyyə vəsaitləri icbari sığorta bazarı üzrə formalaşmış ehtiyatların ən azı 5%-ni qarşılamalıdır. Göstəricinin 5%-dən aşağı düşməsi risk limitinin pozulması hesab edilir.",
    risk_category: "market",
    formula: "(Fondun vəsaiti / İcbari sığorta üzrə bazar ehtiyatı) x100%",
    data_source: "Database (verilənlər bazası)",
    risk_owner: "Aktuar",
    unit: "Faiz",
    frequency: "annual",
    period_values: {"Q1":[null,null,null],"Q2":[null,null,null]},
    trend: "flat",
    threshold_green: ">15%",
    threshold_amber: "5%-15%",
    threshold_red: "<5%",
    current_status: "green",
    appetite_limit: "Aşağı",
    appetite_breach: false,
    created_at: NOW,
    updated_at: NOW,
  },
]
