// Auto-generated from RAS_updated_reviewed_redesigned 04.08.2026.xlsx (RIB sheet)
// 18 Risk Appetite Statement (RAS) indicators → KRIItem seed data
// English rendering of the AZ source; the source workbook remains authoritative.
import type { KRIItem } from '@/types'

export const SEED_RAS_KRIS: KRIItem[] = [
  {
    id: 'ras-001-0000-0000-0000-0000000000001',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-001',
    name: 'Negative and image-damaging information published in the media',
    description: 'The Bureau applies a low-tolerance principle regarding the impact of negative news, information, and commentary published in the mass media. A zero-tolerance risk strategy has been chosen for content that creates very high reputational risks, and the monitoring, assessment, and prompt response to such cases are carried out in line with the company’s communications and risk management procedures. In line with the risk acceptance policy, graded (except for high and very high risks) and short-term negative information may be accepted within the established management mechanisms.',
    risk_category: 'reputation',
    formula: '(Negative news, information, and comments published in the mass media during the period / Total media items during the period) x100%',
    data_source: 'Media monitoring system',
    unit: 'Percent',
    frequency: 'monthly',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '<4%',
    threshold_amber: '4%-5%',
    threshold_red: '>5%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-002-0000-0000-0000-0000000000002',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-002',
    name: 'Recovery Time (RTO)',
    description: 'The Bureau has a low risk appetite for service interruptions in critical business processes and does not tolerate a per-incident service recovery time exceeding 2 hours.',
    risk_category: 'information_security',
    formula: 'Total downtime that occurred in the system during the period and the recovery time for that downtime',
    data_source: 'Information security tools',
    unit: 'Hours',
    frequency: 'monthly',
    current_value: 0.43,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '<1',
    threshold_amber: '1-2',
    threshold_red: '>2',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-003-0000-0000-0000-0000000000003',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-003',
    name: 'Recovery Point Objective (RPO)',
    description: 'The organization shows zero tolerance for data loss in critical information systems. Under the zero-tolerance requirement, any value greater than 0 is treated as a limit breach.',
    risk_category: 'information_security',
    formula: 'The maximum acceptable data-loss window when an event (interruption, system failure, cyber incident, etc.) occurs during the period (in line with the backup strategy)',
    data_source: 'Information security tools',
    unit: 'Hours',
    frequency: 'monthly',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '',
    threshold_amber: '',
    threshold_red: '>0',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-004-0000-0000-0000-0000000000004',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-004',
    name: 'Transfer of sensitive data (DLP)',
    description: 'The transfer of sensitive data (data considered confidential that is not in the public-information category, personal data, and insurance data) to other parties is not permitted. Under the zero-tolerance requirement, any value greater than 0 is treated as a limit breach.',
    risk_category: 'information_security',
    formula: 'Attempts and occurrences during the period (the number of leaks/transfers of sensitive and confidential data by physical means or electronically)',
    data_source: 'Information security tools',
    unit: 'Times',
    frequency: 'monthly',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '',
    threshold_amber: '',
    threshold_red: '>0',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-005-0000-0000-0000-0000000000005',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-005',
    name: 'Interruptions in sector-affecting business processes',
    description: 'During the period, the total number of unplanned outages in critical systems affecting the sector within the business process must not exceed 4.',
    risk_category: 'information_security',
    formula: 'Number of unplanned outages in the business process during the period',
    data_source: 'Information security tools',
    unit: 'Times',
    frequency: 'monthly',
    current_value: 1.0,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '≤1',
    threshold_amber: '2-3',
    threshold_red: '≥4',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-006-0000-0000-0000-0000000000006',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-006',
    name: 'Remediation of risks and events arising during the period and of audit findings',
    description: 'The Bureau applies a low-tolerance principle to the number and percentage of all very high and high events overdue for remediation during the period. When the percentage of events, risks, and audit findings rated very high and high in any period exceeds the established threshold, prompt investigation and preventive measures are carried out and immediately escalated. Minimal, low, and medium events, audit findings, and risks are tracked and managed within the established procedures.',
    risk_category: 'compliance',
    formula: '(High and very high rated risks, events, and audit findings overdue for remediation during the period / High and very high rated risks, events, and audit findings awaiting resolution during the period) x100%',
    data_source: 'JIRA',
    unit: 'Percent',
    frequency: 'quarterly',
    current_value: 0.006,
    previous_value: 0.01,
    trend: 'flat',
    threshold_green: '<5%',
    threshold_amber: '5%-15%',
    threshold_red: '>15%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-007-0000-0000-0000-0000000000007',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-007',
    name: 'Unanswered Calls',
    description: 'To ensure the continuity of customer service, the level of unanswered calls must not exceed 10%. Values above 10% require immediate corrective action.',
    risk_category: 'compliance',
    formula: '(Unanswered calls during the period / Total incoming calls during the period) x100%',
    data_source: 'Complaint/Incident registration system',
    unit: 'Percent',
    frequency: 'monthly',
    current_value: 0.0424,
    previous_value: 0.08,
    trend: 'flat',
    threshold_green: '<5%',
    threshold_amber: '5%-10%',
    threshold_red: '>10%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-008-0000-0000-0000-0000000000008',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-008',
    name: 'Employee turnover',
    description: 'The organization aims to keep employee turnover at a manageable level and, taking the natural variability of the labor market into account, accepts employee losses of up to 20%. However, because an excessive rise in turnover negatively affects operational stability, knowledge continuity, and service quality within the organization, this indicator is actively monitored within the risk appetite, and management measures are taken if the established limits are exceeded.',
    risk_category: 'operational',
    formula: '(Number of employees who left during the period / 12-month average headcount) x100%',
    data_source: 'ITSM, 1C ERP',
    unit: 'Percent',
    frequency: 'monthly',
    current_value: 0.0099,
    previous_value: 0.0103,
    trend: 'flat',
    threshold_green: '<10%',
    threshold_amber: '10%-20%',
    threshold_red: '>20%',
    current_status: 'green',
    appetite_limit: 'Medium',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-009-0000-0000-0000-0000000000009',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-009',
    name: 'Critical employee turnover',
    description: 'The Bureau applies a low-tolerance principle to employee turnover during the period. When the percentage of critical employees leaving during the period exceeds the established threshold, the Human Resources Committee immediately investigates the causes and implements appropriate corrective measures.',
    risk_category: 'operational',
    formula: '(Number of critical employees who left during the period / 12-month average number of critical employees) x100%',
    data_source: 'ITSM, 1C ERP',
    unit: 'Percent',
    frequency: 'monthly',
    current_value: 0.037,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '<5%',
    threshold_amber: '5%-10%',
    threshold_red: '>10%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-010-0000-0000-0000-0000000000010',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-010',
    name: 'Operational losses',
    description: 'The company has a low risk appetite for operational losses. The amount and frequency of operational losses must be kept within the established limits, recurring events must be minimized, and all significant operational events must be investigated in a timely manner with corrective measures implemented. The company applies zero tolerance to operational losses arising from internal-control deficiencies, fraud, and serious process violations.',
    risk_category: 'operational',
    formula: 'Total amount of operational losses recorded during the period',
    data_source: '1C ERP',
    unit: 'AZN',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '<10000',
    threshold_amber: '10000-100 000',
    threshold_red: '>100 000',
    current_status: 'green',
    appetite_limit: 'Medium',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-011-0000-0000-0000-0000000000011',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-011',
    name: 'Open currency position',
    description: 'A low-tolerance principle is applied to the difference between currency assets and liabilities. If the difference between currency assets and liabilities exceeds the established threshold during the period, risk management measures are activated immediately.',
    risk_category: 'financial',
    formula: '(Net open currency position / Capital) x100%',
    data_source: '1C ERP',
    unit: 'Percent',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '<5%',
    threshold_amber: '5–10%',
    threshold_red: '>10%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-012-0000-0000-0000-0000000000012',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-012',
    name: 'Liquidity shortfall',
    description: 'The company aims to hold sufficient high-quality liquid assets to meet its short-term liquidity obligations fully and on time. The company does not accept the liquidity ratio falling below the established minimum level (100%), and in such cases a liquidity recovery plan is triggered immediately.',
    risk_category: 'financial',
    formula: 'LCR = (HQLA / Net Cash Outflow, 30 days) x100% Liquidity Coverage Ratio = (High-quality liquid assets / Total net cash outflow over the next 30 calendar days) x 100%',
    data_source: '1C ERP',
    unit: 'Percent',
    frequency: 'annual',
    current_value: 622.865231,
    previous_value: 441.942075,
    trend: 'flat',
    threshold_green: '>120%',
    threshold_amber: '120%-100%',
    threshold_red: '<100%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-013-0000-0000-0000-0000000000013',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-013',
    name: 'Expected credit loss on the investment portfolio',
    description: 'When managing its investment portfolio, the Bureau prioritizes keeping portfolio risk to a minimum and has drawn up its investment policy conservatively.',
    risk_category: 'financial',
    formula: '(ECL (allowance for credit losses) balance / Total investment portfolio) x100%',
    data_source: '1C ERP',
    unit: 'Percent',
    frequency: 'annual',
    current_value: 0.0044,
    previous_value: 0.0044,
    trend: 'flat',
    threshold_green: '<1%',
    threshold_amber: '1-2%',
    threshold_red: '>2%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-014-0000-0000-0000-0000000000014',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-014',
    name: 'Reserve Adequacy',
    description: 'The Bureau does not accept a reserve shortfall.',
    risk_category: 'financial',
    formula: 'Reserve Adequacy Ratio = (Technical reserves of the Guarantee Fund / Expected liabilities) ​x100%',
    data_source: 'Database',
    unit: 'Percent',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '>110%',
    threshold_amber: '100–110%',
    threshold_red: '<100%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-015-0000-0000-0000-0000000000015',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-015',
    name: 'Stress resilience of the Guarantee Fund',
    description: 'At any time, the Fund must maintain the financial resilience to meet the resolution rules and all legally approved statutory obligations in a scenario where at least the single largest participating insurer fails to meet its obligations. As a result of the stress test, the coverage ratio must not fall below 100%.',
    risk_category: 'financial',
    formula: '(Available Guarantee Fund / Liability required to be paid by the Fund under the stress scenario) x100%',
    data_source: 'Database',
    unit: 'Percent',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '>110%',
    threshold_amber: '100%-110%',
    threshold_red: '<100%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-016-0000-0000-0000-0000000000016',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-016',
    name: 'Liquidity of the Guarantee Fund',
    description: 'Liquid assets must make up at least 5% of the reserves for the compulsory insurance market so that short-term payment obligations are met without delay.',
    risk_category: 'financial',
    formula: '(Liquid assets / Market reserve for compulsory insurance) x100%',
    data_source: 'Database',
    unit: 'Percent',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '>10%',
    threshold_amber: '5%-10%',
    threshold_red: '<5%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-017-0000-0000-0000-0000000000017',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-017',
    name: 'Guarantee Fund coverage of the IBNR reserve',
    description: 'The ratio of the incurred-but-not-reported losses (IBNR) reserve to the market reserve must be kept within the range determined by actuarial calculations, at a 100% limit. Deviation from this range requires re-assessment of the reserves.',
    risk_category: 'financial',
    formula: '(Guarantee Fund resources / IBNR reserve) x100%',
    data_source: 'Database',
    unit: 'Percent',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '>110%',
    threshold_amber: '100%-110%',
    threshold_red: '<100%',
    current_status: 'green',
    appetite_limit: 'Medium',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ras-018-0000-0000-0000-0000000000018',
    org_id: '00000000-0000-0000-0000-000000000001',
    kri_id: 'RAS-018',
    name: 'Market coverage of the Guarantee Fund',
    description: 'The Fund’s financial resources must cover at least 5% of the reserves formed for the compulsory insurance market. The indicator falling below 5% is treated as a breach of the risk limit.',
    risk_category: 'financial',
    formula: '(Fund resources / Market reserve for compulsory insurance) x100%',
    data_source: 'Database',
    unit: 'Percent',
    frequency: 'annual',
    current_value: undefined,
    previous_value: undefined,
    trend: 'flat',
    threshold_green: '>15%',
    threshold_amber: '5%-15%',
    threshold_red: '<5%',
    current_status: 'green',
    appetite_limit: 'Low',
    appetite_breach: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
