'use client'

import { motion } from 'framer-motion'
import { Zap, AlertTriangle, Info, TrendingUp } from 'lucide-react'
import type { AiInsight } from '@/types'
import { cn } from '@/lib/utils'

const severityConfig = {
  critical: {
    icon: AlertTriangle,
    border: 'border-red-500/30',
    bg: 'bg-red-500/5',
    iconColor: 'text-red-500',
    badge: 'bg-red-500/15 text-red-500',
    label: 'Critical',
  },
  warning: {
    icon: TrendingUp,
    border: 'border-orange-500/30',
    bg: 'bg-orange-500/5',
    iconColor: 'text-orange-500',
    badge: 'bg-orange-500/15 text-orange-500',
    label: 'Warning',
  },
  info: {
    icon: Info,
    border: 'border-blue-500/30',
    bg: 'bg-blue-500/5',
    iconColor: 'text-blue-500',
    badge: 'bg-blue-500/15 text-blue-500',
    label: 'Info',
  },
}

interface Props { insights: AiInsight[] }

export function AiInsightsPanel({ insights }: Props) {
  return (
    <div className="card p-5">
      <div className="flex items-center gap-2 mb-5">
        <div className="flex items-center justify-center w-7 h-7 rounded-lg bg-indigo-600">
          <Zap className="w-3.5 h-3.5 text-white" />
        </div>
        <div>
          <h3 className="text-sm font-semibold" style={{ color: 'var(--foreground)' }}>AI Insights</h3>
          <p className="text-[11px]" style={{ color: 'var(--muted-fg)' }}>Generated by OpenAI GPT-4o</p>
        </div>
        <span className="ml-auto text-[10px] px-2 py-0.5 rounded-full bg-indigo-500/15 text-indigo-500 font-medium">
          Live
        </span>
      </div>

      <div className="space-y-3">
        {insights.map((insight, i) => {
          const config = severityConfig[insight.severity]
          const Icon = config.icon
          return (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 + i * 0.1 }}
              className={cn('p-4 rounded-xl border', config.border, config.bg)}
            >
              <div className="flex items-start gap-3">
                <Icon className={cn('w-4 h-4 mt-0.5 shrink-0', config.iconColor)} />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <p className="text-xs font-semibold" style={{ color: 'var(--foreground)' }}>
                      {insight.title}
                    </p>
                    <span className={cn('text-[10px] px-1.5 py-0.5 rounded-full font-medium', config.badge)}>
                      {config.label}
                    </span>
                  </div>
                  <p className="text-xs leading-relaxed" style={{ color: 'var(--muted-fg)' }}>
                    {insight.content}
                  </p>
                </div>
              </div>
            </motion.div>
          )
        })}
      </div>

      <button className="w-full mt-4 py-2 text-xs font-medium text-indigo-500 hover:text-indigo-400 transition-colors border border-indigo-500/20 rounded-lg hover:bg-indigo-500/5">
        Generate Fresh Insights ↗
      </button>
    </div>
  )
}
